### ISSUE TITLE
[Question] `element.replace (backup)`

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/matlab-ephemeris-py#4]
Hi, @Ranplax,

You just pushed a set of bugfixes.  What was the issue about the original line `element.rename (backup)` such that it had to be adjusted?

**Comment by NiklasLeukroth** [comment]
You can find the official documentation here: https://docs.python.org/3/library/pathlib.html#pathlib.Path.replace

The main point is, that rename raises an error on windows, while replace does not. I am sure there is a way, to make it work using rename, but this seemed like a simple enough solution to work on both platforms.

"
Path.rename(target)
Rename this file or directory to the given target, and return a new Path instance pointing to target. On Unix, if target exists and is a file, it will be replaced silently if the user has permission. On Windows, if target exists, [FileExistsError](https://docs.python.org/3/library/exceptions.html#FileExistsError) will be raised. target can be either a string or another path object:
"

**Comment by kevinmatthes** [comment]
Okay, this answers the question.  Thanks!  :+1:
